/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ApiCheckoutCreateRouteImport } from './routes/api/checkout/create'
import { Route as ApiPublicPagarmeWebhookRouteImport } from './routes/api/public/pagarme-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutCreateRoute = ApiCheckoutCreateRouteImport.update({
  id: '/api/checkout/create',
  path: '/api/checkout/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPagarmeWebhookRoute = ApiPublicPagarmeWebhookRouteImport.update({
  id: '/api/public/pagarme-webhook',
  path: '/api/public/pagarme-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/checkout/create': typeof ApiCheckoutCreateRoute
  '/api/public/pagarme-webhook': typeof ApiPublicPagarmeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/checkout/create': typeof ApiCheckoutCreateRoute
  '/api/public/pagarme-webhook': typeof ApiPublicPagarmeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/checkout/create': typeof ApiCheckoutCreateRoute
  '/api/public/pagarme-webhook': typeof ApiPublicPagarmeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/checkout' | '/api/checkout/create' | '/api/public/pagarme-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/api/checkout/create' | '/api/public/pagarme-webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/api/checkout/create'
    | '/api/public/pagarme-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiCheckoutCreateRoute: typeof ApiCheckoutCreateRoute
  ApiPublicPagarmeWebhookRoute: typeof ApiPublicPagarmeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/create': {
      id: '/api/checkout/create'
      path: '/api/checkout/create'
      fullPath: '/api/checkout/create'
      preLoaderRoute: typeof ApiCheckoutCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pagarme-webhook': {
      id: '/api/public/pagarme-webhook'
      path: '/api/public/pagarme-webhook'
      fullPath: '/api/public/pagarme-webhook'
      preLoaderRoute: typeof ApiPublicPagarmeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ApiCheckoutCreateRoute: ApiCheckoutCreateRoute,
  ApiPublicPagarmeWebhookRoute: ApiPublicPagarmeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
